-- MySQL Script generated by MySQL Workbench
-- Thu Dec 12 12:56:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Booking` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Booking` (
  `Booking_ID` INT NOT NULL AUTO_INCREMENT,
  `TableNo` INT NOT NULL,
  `GuestFirstName` VARCHAR(45) NOT NULL,
  `GuestLastName` VARCHAR(45) NOT NULL,
  `BookingSlot` TIME NOT NULL,
  `Staff_ID` INT NOT NULL,
  PRIMARY KEY (`Booking_ID`),
  UNIQUE INDEX `BookingSlot_UNIQUE` (`BookingSlot` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Staff` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Staff` (
  `Staff_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `Contact_Number` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Annual_Salary` VARCHAR(45) NULL,
  PRIMARY KEY (`Staff_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Menu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `Item_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  `Price` INT NOT NULL,
  `Staff_ID` INT NOT NULL,
  PRIMARY KEY (`Item_ID`),
  INDEX `Staff_ID_idx` (`Staff_ID` ASC) VISIBLE,
  CONSTRAINT `Staff_ID`
    FOREIGN KEY (`Staff_ID`)
    REFERENCES `mydb`.`Staff` (`Staff_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu_Table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Menu_Table` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Menu_Table` (
  `Menu_ID` INT NOT NULL,
  `Item_ID` INT NOT NULL,
  `Cuisine` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Menu_ID`),
  CONSTRAINT `Item_ID`
    FOREIGN KEY (`Menu_ID`)
    REFERENCES `mydb`.`Menu` (`Item_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Orders` (
  `Order_ID` INT NOT NULL,
  `TableNo` INT NOT NULL,
  `Menu_ID` INT NOT NULL,
  `Booking_ID` INT NOT NULL,
  `Bill_Amount` INT NULL,
  `Quantity` INT NULL,
  PRIMARY KEY (`Order_ID`),
  INDEX `Booking_ID_idx` (`Booking_ID` ASC) VISIBLE,
  INDEX `Menu_ID_idx` (`Menu_ID` ASC) VISIBLE,
  CONSTRAINT `Booking_ID`
    FOREIGN KEY (`Booking_ID`)
    REFERENCES `mydb`.`Booking` (`Booking_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Menu_ID`
    FOREIGN KEY (`Menu_ID`)
    REFERENCES `mydb`.`Menu_Table` (`Menu_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
