insert into `bookings` (`booking_id`, `booking_slot`, `booking_type`, `comment`, `total_number_of_guests`) values (1, '2024-12-20 18:00:00', 'Family', 'Anniversary dinner', 4);
insert into `bookings` (`booking_id`, `booking_slot`, `booking_type`, `comment`, `total_number_of_guests`) values (2, '2024-12-20 19:30:00', 'Couple', 'Window seat requested', 2);
insert into `bookings` (`booking_id`, `booking_slot`, `booking_type`, `comment`, `total_number_of_guests`) values (3, '2024-12-21 13:00:00', 'Friends', 'Birthday celebration', 6);
insert into `bookings` (`booking_id`, `booking_slot`, `booking_type`, `comment`, `total_number_of_guests`) values (4, '2024-12-21 20:00:00', 'Solo', 'Quiet corner seat', 1);
insert into `bookings` (`booking_id`, `booking_slot`, `booking_type`, `comment`, `total_number_of_guests`) values (5, '2024-12-22 14:00:00', 'Business', 'Quick lunch', 3);
insert into `bookings` (`booking_id`, `booking_slot`, `booking_type`, `comment`, `total_number_of_guests`) values (6, '2024-12-22 19:00:00', 'Family', 'No peanuts in the food', 5);
insert into `bookings` (`booking_id`, `booking_slot`, `booking_type`, `comment`, `total_number_of_guests`) values (7, '2024-12-23 18:30:00', 'Group', 'Outdoor seating requested', 8);
insert into `bookings` (`booking_id`, `booking_slot`, `booking_type`, `comment`, `total_number_of_guests`) values (8, '2024-12-24 12:00:00', 'Team', 'Vegetarian menu only', 10);
insert into `bookings` (`booking_id`, `booking_slot`, `booking_type`, `comment`, `total_number_of_guests`) values (9, '2024-12-24 20:00:00', 'Friends', 'Bring a cake to the table', 7);
insert into `bookings` (`booking_id`, `booking_slot`, `booking_type`, `comment`, `total_number_of_guests`) values (10, '2024-12-25 19:00:00', 'Couple', 'Celebrating anniversary', 4);
